# -*- coding: utf-8 -*-
"""가치배당.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvGOwdsxOPWNOXlgsE3OtZs5YfXnq6hw
"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 1. 설치된 나눔바른고딕의 실제 경로 확인
font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font_name = fm.FontProperties(fname=font_path).get_name()

# 2. Matplotlib에 강제 설정
plt.rc('font', family=font_name)
plt.rcParams['axes.unicode_minus'] = False

# 3. 테스트 (제목이 잘 나오는지 확인)
plt.title('한글 테스트 - 이제는 보여야 합니다')
plt.plot([1,2,3], [1,2,3])
plt.show()

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# change directory to where you have your data file!!
# %cd gdrive/MyDrive/etf/data

"""#가치배당"""

import pandas as pd
import numpy as np
import os
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

def run_quant_clustering_from_list(file_list, n_clusters=3, freq='Q'):
    price_data = {}
    print(f"📂 총 {len(file_list)}개 파일 읽기 시작...")

    for file in file_list:
        try:
            basename = os.path.basename(file)
            parts = basename.split('_')
            etf_name = f"{parts[0]}_{parts[1]}"
            df = pd.read_csv(file)
            df['날짜'] = pd.to_datetime(df['날짜'])
            df.set_index('날짜', inplace=True)
            col_name = '종가' if '종가' in df.columns else df.columns[0]
            price_data[etf_name] = df[col_name]
        except Exception as e:
            continue

    # [수정] 데이터프레임 생성 및 열 이름 정렬
    full_df = pd.DataFrame(price_data).sort_index()
    full_df = full_df.reindex(sorted(full_df.columns), axis=1) # 컬럼 순서 고정
    full_df = full_df.ffill()
    returns_df = full_df.pct_change()

    rebalance_dates = pd.date_range(start=full_df.index.min(), end=full_df.index.max(), freq=freq)
    final_cluster_features = []

    for i in range(1, len(rebalance_dates)):
        end_date = rebalance_dates[i]
        lookback_start = end_date - pd.Timedelta(days=365)
        train_data = returns_df.loc[lookback_start:end_date].dropna(axis=1)

        if train_data.empty or train_data.shape[1] < n_clusters:
            continue

        scaler = StandardScaler()
        scaled_train = scaler.fit_transform(train_data.T)

        # random_state 고정
        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        cluster_labels = kmeans.fit_predict(scaled_train)

        # --- [핵심 추가: 군집 번호 정렬 로직] ---
        # 군집별 평균 수익률을 계산하여 수익률이 낮은 순서대로 0, 1, 2번을 다시 부여합니다.
        cluster_info = pd.DataFrame({'label': cluster_labels, 'ret': train_data.mean()})
        # 군집별 평균 수익률 순위 계산
        rank_map = cluster_info.groupby('label')['ret'].mean().sort_values().index
        # 기존 라벨을 수익률 순위 라벨로 변경
        new_label_map = {old: new for new, old in enumerate(rank_map)}
        fixed_labels = np.array([new_label_map[label] for label in cluster_labels])

        cluster_map = pd.Series(fixed_labels, index=train_data.columns)
        # ------------------------------------------

        next_end = rebalance_dates[i+1] if i+1 < len(rebalance_dates) else full_df.index.max()
        target_returns = returns_df.loc[end_date:next_end]
        period_features = pd.DataFrame(index=target_returns.index)

        for c in range(n_clusters):
            members = cluster_map[cluster_map == c].index
            active_returns = target_returns[members]
            period_features[f'C{c}_Ret'] = active_returns.mean(axis=1)
            period_features[f'C{c}_Disp'] = active_returns.std(axis=1)
            period_features[f'C{c}_Vol'] = period_features[f'C{c}_Ret'].rolling(window=20, min_periods=5).std()
            period_features[f'C{c}_Count'] = active_returns.notna().sum(axis=1)

        final_cluster_features.append(period_features)
        print(f"📡 {end_date.date()} 기준 군집화 완료 (수익률 순 정렬 적용)")

    if final_cluster_features:
        final_df = pd.concat(final_cluster_features).sort_index()
        return final_df[~final_df.index.duplicated(keep='first')]
    return None

# --- 메인 실행부 ---

# 1. 수집된 파일 경로 리스트 (제공해주신 리스트)
collected_files = [
    "TIGER_미국다우존스30_245340_2019_2025.csv",
    "TIGER_미국배당다우존스_458730_2019_2025.csv",
    "SOL_미국배당다우존스_446720_2019_2025.csv",
    "ACE_미국배당다우존스_402970_2019_2025.csv",
    "SOL_미국배당다우존스_452360_2019_2025.csv",
    "TIGER_미국MSCI리츠(합성_H)_182480_2019_2025.csv",
    "TIGER_미국S&P500배당귀족_429000_2019_2025.csv",
    "TIGER_미국나스닥바이오_203780_2019_2025.csv",
    "KODEX_미국부동산리츠_352560_2019_2025.csv",
    "SOL_미국배당다우존스TR_493420_2019_2025.csv",
    "KODEX_미국S&P500헬스케어_453640_2019_2025.csv",
    "KODEX_미국S&P바이오(합성)_185680_2019_2025.csv",
    "RISE_미국S&P배당킹_460660_2019_2025.csv",
    "ACE_테슬라밸류체인액티브_457480_2019_2025.csv",
    "PLUS_고배당주_161510_2019_2025.csv",
    "KODEX_미국AI전력핵심인프라_487230_2019_2025.csv",
    "KODEX_은행_091170_2019_2025.csv",
    "TIGER_은행고배당플러스TOP10_466940_2019_2025.csv",
    "TIGER_200_헬스케어_227540_2019_2025.csv",
    "TIGER_로우볼_174350_2019_2025.csv",
    "TIGER_우량가치_227570_2019_2025.csv"
]

# 2. 파이프라인 가동
output_path = "TFT_Quant_Input_Features_가치배당.csv"
final_tft_input = run_quant_clustering_from_list(collected_files, n_clusters=3, freq='Q')

# 3. 결과 저장
if final_tft_input is not None:
    final_tft_input.to_csv(output_path, encoding='utf-8-sig')
    print(f"\n✅ 퀀트 피처 생성 완료 및 저장: {output_path}")
    print(final_tft_input.tail())
else:
    print("\n❌ 데이터 생성 실패. 파일 경로를 다시 확인해주세요.")

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
import os

def visualize_quant_pipeline(final_df):
    # 1. 스타일 설정
    sns.set_style("whitegrid")

    # 2. 폰트 설정 (환경에 따라 자동 선택)
    if os.path.exists('/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'):
        # 코랩 환경
        font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
    elif os.path.exists('/System/Library/Fonts/Supplemental/AppleGothic.ttf'):
        # 맥(Mac) 로컬 환경
        font_path = '/System/Library/Fonts/Supplemental/AppleGothic.ttf'
    else:
        # 윈도우 또는 기타 (기본 폰트 사용)
        font_path = None

    if font_path:
        font_name = fm.FontProperties(fname=font_path).get_name()
        plt.rc('font', family=font_name)

    plt.rcParams['axes.unicode_minus'] = False

    fig, axes = plt.subplots(3, 1, figsize=(15, 20))

    # --- 1. 군집별 누적 수익률 ---
    return_cols = [c for c in final_df.columns if '_Ret' in c]
    # 군집 번호순(C0, C1, C2)으로 정렬하여 출력
    return_cols.sort()
    cum_returns = (1 + final_df[return_cols].fillna(0)).cumprod() * 100

    for col in cum_returns.columns:
        axes[0].plot(cum_returns.index, cum_returns[col], label=col, linewidth=2.5)

    axes[0].set_title('① 군집별 누적 수익률 추이 (수익률 순위 고정: C0 낮은순 -> C2 높은순)', fontsize=16, fontweight='bold', pad=15)
    axes[0].set_ylabel('지수 가치 (Base=100)')
    axes[0].legend(loc='upper left')

    # --- 2. 군집별 종목 수 ---
    count_cols = [c for c in final_df.columns if '_Count' in c]
    count_cols.sort()
    axes[1].stackplot(final_df.index, [final_df[col] for col in count_cols], labels=count_cols, alpha=0.6)
    axes[1].set_title('② 시점별 군집 내 포함된 ETF 종목 수 변화', fontsize=16, fontweight='bold', pad=15)
    axes[1].set_ylabel('종목 수 (Count)')
    axes[1].legend(loc='upper left')

    # --- 3. 군집 내 분산 ---
    disp_cols = [c for c in final_df.columns if '_Disp' in c]
    disp_cols.sort()
    for col in disp_cols:
        axes[2].plot(final_df.index, final_df[col].rolling(window=20).mean(), label=col, alpha=0.8)

    axes[2].set_title('③ 군집 내 수익률 분산 (Dispersion: 낮을수록 응집도 높음)', fontsize=16, fontweight='bold', pad=15)
    axes[2].set_ylabel('수익률 표준편차 (20일 MA)')
    axes[2].set_xlabel('날짜 (Date)')
    axes[2].legend(loc='upper left')

    plt.tight_layout()
    plt.show()

# 실행
if 'final_tft_input' in locals() and final_tft_input is not None:
    visualize_quant_pipeline(final_tft_input)
else:
    print("❌ 데이터를 먼저 생성해 주세요.")

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def visualize_cluster_membership(file_list, n_clusters=3, freq='Q'):
    # --- [데이터 처리 로직] ---
    price_data = {}
    for file in file_list:
        try:
            basename = os.path.basename(file)
            etf_name = f"{basename.split('_')[0]}_{basename.split('_')[1]}"
            df = pd.read_csv(file, encoding='utf-8-sig')

            df.iloc[:, 0] = pd.to_datetime(df.iloc[:, 0], errors='coerce')
            df = df.dropna(subset=[df.columns[0]])
            df.set_index(df.columns[0], inplace=True)

            price_data[etf_name] = df.iloc[:, 0]
        except: continue

    # 1. 데이터프레임 생성 및 '열 이름 순서' 고정
    full_df = pd.DataFrame(price_data).sort_index()
    full_df = full_df.reindex(sorted(full_df.columns), axis=1) # 컬럼 순서 정렬
    full_df = full_df.ffill()
    returns_df = full_df.pct_change()

    rebalance_dates = pd.date_range(start=full_df.index.min(), end=full_df.index.max(), freq=freq)

    membership_history = []

    for i in range(1, len(rebalance_dates)):
        end_date = rebalance_dates[i]
        lookback_start = end_date - pd.Timedelta(days=365)
        train_data = returns_df.loc[lookback_start:end_date].dropna(axis=1)

        if train_data.empty or train_data.shape[1] < n_clusters: continue

        scaler = StandardScaler()
        scaled_train = scaler.fit_transform(train_data.T)

        # random_state 고정
        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        cluster_labels = kmeans.fit_predict(scaled_train)

        # --- [핵심 추가: 군집 번호를 수익률 순서대로 재매핑] ---
        # 이 로직이 있어야 돌릴 때마다 번호(색상)가 바뀌지 않습니다.
        cluster_info = pd.DataFrame({'label': cluster_labels, 'ret': train_data.mean()})
        # 수익률 낮은 군집부터 0, 1, 2 순서 부여
        rank_map = cluster_info.groupby('label')['ret'].mean().sort_values().index
        new_label_map = {old: new for new, old in enumerate(rank_map)}
        fixed_labels = [new_label_map[label] for label in cluster_labels]
        # ---------------------------------------------------

        period_membership = pd.Series(fixed_labels, index=train_data.columns, name=end_date.date())
        membership_history.append(period_membership)

    # 데이터프레임 통합 (행: ETF, 열: 날짜) 및 종목 이름순 정렬
    membership_df = pd.concat(membership_history, axis=1).sort_index()

    # --- [시각화 설정] ---
    sns.set_style("white")

    # 코랩/맥 환경에 따른 폰트 경로 자동 설정
    font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
    if not os.path.exists(font_path): # 맥 환경일 경우
        font_path = '/System/Library/Fonts/Supplemental/AppleGothic.ttf'

    font_prop = fm.FontProperties(fname=font_path)
    plt.rc('font', family=font_prop.get_name())
    plt.rcParams['axes.unicode_minus'] = False

    plt.figure(figsize=(22, 12))
    # cmap='viridis' (0: 보라, 1: 초록, 2: 노랑)
    sns.heatmap(membership_df, annot=True, cmap='viridis', cbar=True, linewidths=.5)

    plt.title('ETF 군집 멤버십 변화 (수익률 기반 라벨 고정: 0=Low, 2=High)', fontsize=20, fontweight='bold', pad=25)
    plt.xlabel('리밸런싱 시점 (Rebalance Date)', fontsize=14, labelpad=15)
    plt.ylabel('ETF 명칭 (알파벳순)', fontsize=14, labelpad=15)
    plt.xticks(rotation=45)

    plt.tight_layout()
    plt.show()

# --- 실행 ---
if 'collected_files' in locals():
    visualize_cluster_membership(collected_files, n_clusters=3)